#
# Travis CI recipe to build glibc binary packages.
#

arch: amd64
os: linux
dist: focal

language: generic

services:
  - docker

env:
  global:
  - GLIBC_VERSION=${TRAVIS_TAG:-2.26}
  matrix:
  - ARCH=x86
  - ARCH=x86_64
  - ARCH=arm
  - ARCH=armhf
  - ARCH=aarch64

before_script:
  # Validate the glibc version format: 'X.XX' or 'X.XX-rY'.
  - '[[ "$GLIBC_VERSION" =~ ^[0-9]+\.[0-9]+(-r[0-9]+)?$ ]]'

script:
  - echo "Starting build of glibc $GLIBC_VERSION for $ARCH..."
  - travis_wait 30 ./build-glibc.sh "$ARCH" "$GLIBC_VERSION" --output build.output

after_failure:
  - 'echo "ERROR: glibc build failed.  Last output:"'
  - tail -n 500 build.output

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
