#
# Travis CI recipe to build glibc binary packages.
#

sudo: required

language: generic

services:
  - docker

env:
  global:
  - GLIBC_VERSION=2.26
  matrix:
  - ARCH=x86
  - ARCH=x86_64
  - ARCH=armhf
  - ARCH=aarch64

before_script:
  - '[ -z "$TRAVIS_TAG" ] || [[ "$TRAVIS_TAG" =~ ^$GLIBC_VERSION-[0-9]+$ ]]'

script:
  - travis_wait 30 ./build-glibc.sh "$ARCH" "$GLIBC_VERSION" --output build.output
  - find .

after_failure:
  - echo "ERROR: glibc build failed.  Last output:"
  - tail -n 500 build.output

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
